// resources/js/Components/MediaManager/MediaUploader.vue
<script lang="ts" setup>
import axios, { AxiosProgressEvent } from 'axios'
import { inject, ref } from 'vue'

// import { openErrorToast } from '@/composables/useSnackbar'
// import { ziggySymbol } from '@/symbols/ziggy'
// import Heading from '../Heading.vue'
import DropZone from './DropZone.vue'
import UploadProgress from './UploadProgress.vue'
import { route as ziggyRoute } from 'ziggy-js'

const progress = ref()
const uploading = ref(false)

// for storing file events
const files = ref<File[]>([])

const input = ref<HTMLInputElement | null>(null)

const route = inject('route') as typeof ziggyRoute

const { multiple = false } = defineProps<{
  multiple?: boolean
}>()

const emit = defineEmits(['uploaded'])

function onInputChange(e: Event) {
  addFiles((e.target! as HTMLInputElement)!.files!)
  input!.value = null
}

function selectNewFile() {
  input.value!.click()
}

// to server
async function addFiles(newFiles: FileList | File) {
  try {
    uploading.value = true
    const formData = new FormData()
    // check if newFiles is array, if not, convert it to array
    if (newFiles instanceof FileList) {
      for (let i = 0; i < newFiles.length; i++) {
        files.value.push(newFiles[i])
        formData.append('media[]', newFiles[i])
      }
    } else {
      files.value = [newFiles]
      formData.append('media[]', newFiles)
    }
    await axios.post(route('media.store'), formData, {
      onUploadProgress: (progressEvent: AxiosProgressEvent) => {
        progress.value = Math.round((progressEvent.loaded * 100) / progressEvent.total!)
      },
    })
    uploading.value = false
    files.value = []
    emit('uploaded')
    // tab.value = 'media'
  } catch (error) {
    // TODO: handle error using snackbar
    if (error instanceof Error) {
      alert(error.message)
      // openErrorToast(error.message)
    } else {
      alert('Something went wrong')
      // openErrorToast()
      console.error(error)
    }
  } finally {
    uploading.value = false
  }
}

</script>

<template>
  <div>
    <UploadProgress
      v-if="uploading"
      :progress="progress"
      :length="files.length"
    />

    <DropZone
      v-else
      v-slot="{ dropZoneActive }"
      class="mt-4"
      :multiple="multiple"
      @files-dropped="addFiles"
    >
      <input
        id="file-input"
        ref="input"
        style="display: none;"
        type="file"
        :multiple="multiple"
        @change="onInputChange"
      >
      <h4 class="text-h6">
        Drop File(s) to Upload
      </h4>
      <div v-if="!dropZoneActive">
        <div class="mb-2">
          or
        </div>
        <v-btn
          variant="outlined"
          @click.prevent="selectNewFile"
        >
          Select File(s)
        </v-btn>
      </div>
    </DropZone>
  </div>
</template>

// resources/js/components/media-manager/media-uploader.svelte
<script lang="ts">
    import AlertCircle from 'lucide-svelte/icons/alert-circle';
    import { store as mediaStore } from '@/actions/App/Http/Controllers/MediaController';
    import * as Alert from '@/components/ui/alert';
    import { Button } from '@/components/ui/button';
    import DropZone from './drop-zone.svelte';
    import UploadProgress from './upload-progress.svelte';

    let progress = $state(0);
    let uploading = $state(false);
    let files = $state<File[]>([]);
    let inputEl: HTMLInputElement | undefined = $state();
    let errors = $state<string[]>([]);

    let {
        multiple = false,
        onuploaded,
    }: {
        multiple?: boolean;
        onuploaded?: (media: App.Data.MediaData[]) => void;
    } = $props();

    function onInputChange(e: Event) {
        const target = e.target as HTMLInputElement;

        if (target.files) {
            addFiles(target.files);
            target.value = '';
        }
    }

    function selectNewFile() {
        inputEl?.click();
    }

    async function addFiles(newFiles: FileList | File) {
        try {
            errors = [];
            uploading = true;
            const formData = new FormData();

            if (newFiles instanceof FileList) {
                for (let i = 0; i < newFiles.length; i++) {
                    files.push(newFiles[i]);
                    formData.append('media[]', newFiles[i]);
                }
            } else {
                files = [newFiles];
                formData.append('media[]', newFiles);
            }

            const xhr = new XMLHttpRequest();
            xhr.open('POST', mediaStore.url());
            xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');

            xhr.upload.onprogress = (e) => {
                if (e.lengthComputable) {
                    progress = Math.round((e.loaded * 100) / e.total);
                }
            };

            await new Promise<void>((resolve, reject) => {
                xhr.onload = () => {
                    if (xhr.status >= 200 && xhr.status < 300) {
                        const response = JSON.parse(xhr.responseText);
                        onuploaded?.(response.data ?? []);
                        resolve();
                    } else if (xhr.status === 422) {
                        const response = JSON.parse(xhr.responseText);
                        const messages: string[] = [];

                        for (const key in response.errors) {
                            messages.push(...response.errors[key]);
                        }

                        errors = messages;
                        reject(new Error('Validation failed'));
                    } else {
                        reject(new Error(xhr.statusText || 'Upload failed'));
                    }
                };
                xhr.onerror = () => reject(new Error('Network error'));
                xhr.send(formData);
            });

            uploading = false;
            files = [];
        } catch (error) {
            if (error instanceof Error && !errors.length) {
                errors = [error.message];
            }
        } finally {
            uploading = false;
        }
    }
</script>

{#if uploading}
    <UploadProgress {progress} length={files.length} />
{:else}
    <DropZone {multiple} onFilesDropped={addFiles}>
        {#snippet child({ active })}
            <div class="text-center">
                <input
                    bind:this={inputEl}
                    type="file"
                    {multiple}
                    class="hidden"
                    onchange={onInputChange}
                />
                <h4 class="font-heading text-lg font-semibold">Drop File(s) to Upload</h4>
                {#if !active}
                    <p class="text-xs text-muted-foreground mb-3">or</p>
                    <Button variant="outline" size="sm" onclick={selectNewFile}>
                        Select File(s)
                    </Button>
                {/if}
            </div>
        {/snippet}
    </DropZone>
{/if}

{#if errors.length > 0}
    <Alert.Root variant="destructive">
        <AlertCircle />
        <Alert.Title>Upload failed</Alert.Title>
        <Alert.Description>
            <ul class="list-inside list-disc text-sm">
                {#each errors as error (error)}
                    <li>{error}</li>
                {/each}
            </ul>
        </Alert.Description>
    </Alert.Root>
{/if}
