// resources/js/Components/MediaManager/MediaSelector.vue
<!-- eslint-disable no-unused-vars -->
<script lang="ts" setup>
import axios from 'axios'
import { ref, watch } from 'vue'

import { Media, PaginatedResponse } from '@/types'
import { imageLink } from '@/composables/useImageLink'
import { mdiCheck } from '@mdi/js'

const props = withDefaults(defineProps<{
  media: PaginatedResponse<Media>
  modelValue?: Media[] | Media | null
  multiple: boolean
}>(), {
  modelValue: null,
  multiple: false,
})

const emit = defineEmits(['update:modelValue', 'selected'])

// for storing paginated media from API
const currentMedia = ref<PaginatedResponse<Media> | null>(null)
// for storing all lazy-loaded media
const loaded = ref<Media[]>([])
// for showing media info on side panel
// const latestSelected = ref<Media | null>()

async function loadMore(url: string | undefined) {
  if (!url) throw new Error('No more media to load')
  // if (date) {
  //   url = `${url}`
  // }
  const { data } = await axios.get<PaginatedResponse<Media>>(`${url}`)
  currentMedia.value = data
  console.log(data)
  loaded.value = [...loaded.value, ...data.data]
}

// function onMediaSelect (item: Media) {
//   // TODO refactor select logic
//   if (!multiple) {
//     if (modelValue === null || (!Array.isArray(modelValue) && modelValue!.id !== item.id)) {
//       emit('update:modelValue', item)
//       emit('selected', item)
//       return
//     }
//     emit('update:modelValue', null)
//   } else {
//     console.log('array')
//     if (!Array.isArray(modelValue)) {
//       throw new Error('selected is not an array')
//     }
//     if (modelValue!.some((i) => i.id === item.id)) {
//       emit('update:modelValue', modelValue!.filter((i) => i.id !== item.id))
//     } else {
//       emit('update:modelValue', [...modelValue, item])
//       emit('selected', item)
//     }
//   }
// }

// onUpdated(async () => {
//   console.log('updated', media)
//   await loadMore(media.path)
// })

function onMediaSelect(item: Media) {
  if (!props.multiple) {
    handleSingleSelect(item)
  } else {
    handleMultipleSelect(item)
  }
}

function handleSingleSelect(item: Media) {
  const isItemSelected = props.modelValue !== null && (Array.isArray(props.modelValue) || props.modelValue!.id === item.id)
  if (!isItemSelected) {
    emit('update:modelValue', item)
    emit('selected', item)
    return
  }
  emit('update:modelValue', null)
  emit('selected', null)
}

function handleMultipleSelect(item: Media) {
  if (!Array.isArray(props.modelValue)) {
    throw new Error('Media Selector v-model is not an array')
  }

  // TODO maybe add check if multiple

  if (isItemSelected(item)) {
    emit('update:modelValue', props.modelValue.filter(i => i.id !== item.id))
    emit('selected', null)
  } else {
    emit('update:modelValue', [...props.modelValue, item])
    emit('selected', item)
  }
}

function isItemSelected(item: Media): boolean {
  if (!Array.isArray(props.modelValue)) {
    throw new Error('Media Selector v-model is not an array')
  }
  return props.modelValue!.some(i => i.id === item.id)
}

watch(() => props.media, (value) => {
  currentMedia.value = value!
  loaded.value = value!.data
})

const selectedIndex = (item: Media) => {
  if (Array.isArray(props.modelValue)) {
    return props.modelValue!.findIndex(({ id }) => id === item.id) + 1
  } else {
    return props.modelValue?.id === item.id
  }
}
</script>

<template>
  <div>
    <h3 class="text-h4">
      Recent Media
    </h3>
    <div class="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
      <v-img
        v-for="item in loaded"
        :key="item.id"
        v-ripple
        :aspect-ratio="1"
        cover
        class="text-right p-2 rounded"
        :src="imageLink(item)?.medium"
        style="cursor: pointer"
        @click="onMediaSelect(item)"
      >
        <!-- <v-btn
            :icon="mdiCheck"
            color="primary"
          /> -->
        <template v-if="selectedIndex(item)">
          <v-btn
            v-if="multiple"
            :icon="true"
            color="primary"
          >
            {{ selectedIndex(item) }}
          </v-btn>
          <v-btn
            v-else
            :icon="mdiCheck"
            color="primary"
          />
        </template>
        <template #placeholder>
          <v-row
            class="fill-height m-0"
            align="center"
            justify="center"
          >
            <v-progress-circular
              indeterminate
              color="grey-lighten-5"
            />
          </v-row>
        </template>
      </v-img>
    </div>
    <div
      v-if="currentMedia?.next_page_url"
      class="text-center"
    >
      <v-btn
        variant="text"
        large
        @click="loadMore(currentMedia?.next_page_url)"
      >
        Load More
      </v-btn>
    </div>
  </div>
</template>

// resources/js/components/media-manager/media-selector.svelte
<script lang="ts">
    import Check from 'lucide-svelte/icons/check';
    import { index as mediaIndex } from '@/actions/App/Http/Controllers/MediaController';
    import { AspectRatio } from '@/components/ui/aspect-ratio';
    import { Button } from '@/components/ui/button';
    import { Spinner } from '@/components/ui/spinner';

    type MediaResponse = App.Data.PaginatedCollection<App.Data.MediaData>;

    let {
        media,
        value = $bindable(null),
        multiple = false,
        onselected,
    }: {
        media: MediaResponse | null;
        value?: App.Data.MediaData | App.Data.MediaData[] | null;
        multiple?: boolean;
        onselected?: (item: App.Data.MediaData | null) => void;
    } = $props();

    let currentMedia = $state<MediaResponse | null>(null);
    let loaded = $state<App.Data.MediaData[]>([]);
    let loading = $state(false);

    async function loadMore() {
        if (
            !currentMedia ||
            currentMedia.currentPage >= currentMedia.lastPage
        ) {
            return;
        }

        const nextPage = currentMedia.currentPage + 1;
        const response = await fetch(
            mediaIndex.url({ query: { page: String(nextPage) } }),
        );
        const data: MediaResponse = await response.json();
        currentMedia = data;
        loaded = [...loaded, ...data.data];
        loading = false;
    }

    $effect(() => {
        if (media) {
            currentMedia = media;
            loaded = media.data;
        }
    });

    function onMediaSelect(item: App.Data.MediaData) {
        if (!multiple) {
            handleSingleSelect(item);
        } else {
            handleMultipleSelect(item);
        }
    }

    function handleSingleSelect(item: App.Data.MediaData) {
        if (
            !value ||
            (Array.isArray(value)
                ? value[0]?.id !== item.id
                : value.id !== item.id)
        ) {
            value = item;
            onselected?.(item);

            return;
        }

        value = null;
        onselected?.(null);
    }

    function handleMultipleSelect(item: App.Data.MediaData) {
        const current = Array.isArray(value) ? value : [];

        if (current.some((i) => i.id === item.id)) {
            value = current.filter((i) => i.id !== item.id);
            onselected?.(null);
        } else {
            value = [...current, item];
            onselected?.(item);
        }
    }

    function isSelected(item: App.Data.MediaData): boolean {
        if (Array.isArray(value)) {
            return value.some((i) => i.id === item.id);
        }

        return value?.id === item.id;
    }

    function selectedIndex(item: App.Data.MediaData): number {
        if (Array.isArray(value)) {
            const idx = value.findIndex((i) => i.id === item.id);

            return idx >= 0 ? idx + 1 : 0;
        }

        return 0;
    }
</script>

<div class="space-y-4">
    <h3 class="font-heading text-lg font-semibold">Recent Media</h3>

    <div class="grid grid-cols-3 gap-3 md:grid-cols-4 lg:grid-cols-5">
        {#each loaded as item (item.id)}
            <button
                type="button"
                class="group relative overflow-hidden rounded-lg border bg-muted cursor-pointer ring-offset-background transition-all hover:ring-2 hover:ring-primary data-[selected=true]:ring-2 data-[selected=true]:ring-primary"
                data-selected={isSelected(item)}
                onclick={() => onMediaSelect(item)}
            >
                <AspectRatio ratio={1}>
                    {#if item.mediumUrl}
                        <img
                            src={item.mediumUrl}
                            alt={item.filename}
                            class="h-full w-full object-cover"
                            loading="lazy"
                        />
                    {:else}
                        <div class="flex h-full items-center justify-center">
                            <span
                                class="text-muted-foreground text-xs p-1 text-center break-all"
                            >
                                {item.filename}.{item.extension}
                            </span>
                        </div>
                    {/if}
                </AspectRatio>
                {#if isSelected(item)}
                    <div class="absolute top-1 right-1">
                        {#if multiple}
                            <span
                                class="flex size-5 items-center justify-center rounded-full bg-primary text-[10px] font-medium text-primary-foreground"
                            >
                                {selectedIndex(item)}
                            </span>
                        {:else}
                            <span
                                class="flex size-5 items-center justify-center rounded-full bg-primary text-primary-foreground"
                            >
                                <Check class="size-3" />
                            </span>
                        {/if}
                    </div>
                {/if}
            </button>
        {/each}
    </div>

    {#if currentMedia && currentMedia.currentPage < currentMedia.lastPage}
        <div class="flex justify-center">
            <Button
                variant="ghost"
                size="sm"
                onclick={loadMore}
                disabled={loading}
            >
                {#if loading}
                    <Spinner class="mr-2 size-4" />
                    Loading...
                {:else}
                    Load More
                {/if}
            </Button>
        </div>
    {/if}
</div>
