// resources/js/Components/MediaManager/MediaRemoteUploader.vue
<script lang="ts" setup>
import axios, { AxiosProgressEvent } from 'axios'
import { inject, ref } from 'vue'

// import { openErrorToast } from '@/scripts/composables/useSnackbar'
// import { SharedData } from '@/types/inertia-page'
// import Validation from '@/views/components/socialstream/Validation.vue'
import UploadProgress from './UploadProgress.vue'
import { route as ziggyRoute } from 'ziggy-js'

const urls = ref<string>('')
const route = inject('route') as typeof ziggyRoute

const progress = ref<number>(0)
const processing = ref(false)
const errorMessage = ref<string>('')
const splitted = ref<string[]>([])

// const inertiaError = usePage().props.errors!
const emit = defineEmits(['uploaded'])

async function upload() {
  try {
    processing.value = true
    console.log(processing)
    splitted.value = urls.value.split(/\r?\n|\r|\n/g).filter(url => (url.trim()))
    // check if each splitted array is valid url
    const validated = splitted.value.filter(url => isValidImageLink(url))
    if (validated.length === 0) {
      throw new Error('There\'s no valid Image URL')
    }
    await axios.post(route('media.store'), {
      url: validated,
    }, {
      onUploadProgress: (e: AxiosProgressEvent) => {
        progress.value = Math.round((e.loaded * 100) / e.total!)
      },
    })
    emit('uploaded')
  } catch (error) {
    if (axios.isAxiosError(error)) {
      errorMessage.value = error.response?.data.message
    } else if (error instanceof Error) {
      alert(error.message)
      // openErrorToast(error.message)
    } else {
      alert('Unknown Error')
      console.error(error)
    }
  } finally {
    urls.value = ''
    splitted.value = []
    progress.value = 0
    processing.value = false
  }
}
function checkURL(url: string) {
  return (url.match(/\.(jpeg|jpg|gif|png)$/) != null)
}

function isValidImageLink(urlToCheck: string) {
  let url: string | URL
  try {
    url = new URL(urlToCheck)
    // check if url is image
    if (!checkURL(urlToCheck)) {
      throw new Error('URL not an image')
    }
  } catch (error) {
    console.error(error)
    return false
  }
  return url.protocol === 'http:' || url.protocol === 'https:'
}

</script>

<template>
  <UploadProgress
    v-if="processing"
    :progress="progress"
    :length="splitted.length"
  />
  <v-form
    :disabled="processing"
    @submit.prevent="upload"
  >
    <!--<Validation :show="Object.keys(inertiaError)" />-->
    <v-textarea
      v-model="urls"
      rows="2"
      :disabled="processing"
      :error-messages="errorMessage"
      class="mt-4"
      label="One URL per line"
      variant="outlined"
    />
    <v-btn
      :disabled="processing"
      variant="outlined"
      type="submit"
    >
      Upload
    </v-btn>
  </v-form>
</template>

// resources/js/components/media-manager/media-remote-uploader.svelte
<script lang="ts">
    import AlertCircle from 'lucide-svelte/icons/alert-circle';
    import { store as mediaStore } from '@/actions/App/Http/Controllers/MediaController';
    import * as Alert from '@/components/ui/alert';
    import { Button } from '@/components/ui/button';
    import { Label } from '@/components/ui/label';
    import { Spinner } from '@/components/ui/spinner';
    import { Textarea } from '@/components/ui/textarea';
    import UploadProgress from './upload-progress.svelte';

    let urls = $state('');
    let progress = $state(0);
    let processing = $state(false);
    let errors = $state<string[]>([]);
    let splitted = $state<string[]>([]);

    let {
        onuploaded,
    }: {
        onuploaded?: (media: App.Data.MediaData[]) => void;
    } = $props();

    function checkURL(url: string) {
        return /\.(jpeg|jpg|gif|png|webp|avif)$/i.test(url);
    }

    function isValidImageLink(urlToCheck: string) {
        try {
            const url = new URL(urlToCheck);

            if (!checkURL(urlToCheck)) {
                return false;
            }

            return url.protocol === 'http:' || url.protocol === 'https:';
        } catch {
            return false;
        }
    }

    async function upload() {
        try {
            errors = [];
            processing = true;
            splitted = urls.split(/\r?\n|\r|\n/g).filter((url) => url.trim());
            const validated = splitted.filter((url) => isValidImageLink(url));

            if (validated.length === 0) {
                errors = ["There's no valid Image URL"];

                return;
            }

            const xhr = new XMLHttpRequest();
            xhr.open('POST', mediaStore.url());
            xhr.setRequestHeader('Content-Type', 'application/json');
            xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');

            xhr.upload.onprogress = (e) => {
                if (e.lengthComputable) {
                    progress = Math.round((e.loaded * 100) / e.total);
                }
            };

            await new Promise<void>((resolve, reject) => {
                xhr.onload = () => {
                    if (xhr.status >= 200 && xhr.status < 300) {
                        const response = JSON.parse(xhr.responseText);
                        onuploaded?.(response.data ?? []);
                        resolve();
                    } else if (xhr.status === 422) {
                        const response = JSON.parse(xhr.responseText);
                        const messages: string[] = [];

                        for (const key in response.errors) {
                            messages.push(...response.errors[key]);
                        }

                        errors = messages;
                        reject(new Error('Validation failed'));
                    } else {
                        reject(new Error(xhr.statusText || 'Upload failed'));
                    }
                };
                xhr.onerror = () => reject(new Error('Network error'));
                xhr.send(JSON.stringify({ url: validated }));
            });
        } catch (error) {
            if (error instanceof Error && !errors.length) {
                errors = [error.message];
            }
        } finally {
            urls = '';
            splitted = [];
            progress = 0;
            processing = false;
        }
    }
</script>

{#if processing}
    <UploadProgress {progress} length={splitted.length} />
{:else}
    <form onsubmit={upload} class="space-y-4">
        <div class="grid gap-2">
            <Label for="remote-urls">One URL per line</Label>
            <Textarea
                id="remote-urls"
                bind:value={urls}
                rows={4}
                disabled={processing}
                placeholder="https://example.com/image.jpg"
            />
        </div>
        <Button type="submit" disabled={processing}>
            {#if processing}
                <Spinner class="mr-2 size-4" />
                Uploading...
            {:else}
                Upload
            {/if}
        </Button>
    </form>
{/if}

{#if errors.length > 0}
    <Alert.Root variant="destructive">
        <AlertCircle />
        <Alert.Title>Upload failed</Alert.Title>
        <Alert.Description>
            <ul class="list-inside list-disc text-sm">
                {#each errors as error (error)}
                    <li>{error}</li>
                {/each}
            </ul>
        </Alert.Description>
    </Alert.Root>
{/if}
