// resources/js/Pages/Anime/Partials/Casts.vue
<script setup lang="ts">
import { AnimeMediaAutofillResponse } from '@/types/anilist'
import { useDisplay } from 'vuetify'

type Props = {
  data: AnimeMediaAutofillResponse
  showTitle?: boolean
}

withDefaults(defineProps<Props>(), {
  showTitle: true,
})

const { smAndUp } = useDisplay()
</script>

<template>
  <div
    v-if="data && data.characters?.edges"
    class="mb-6"
  >
    <v-card-title
      v-if="showTitle"
    >
      Casts
    </v-card-title>
    <div class="grid grid-cos-1 md:grid-cols-2 gap-4 text-body-2">
      <v-card
        v-for="character in data.characters.edges"
        :key="character.node.id"
        :rounded="smAndUp"
      >
        <div
          class="grid grid-cols-2"
        >
          <div class="grid grid-cols-4">
            <v-img
              :src="character.node.image.large"
              :lazy-src="character.node.image.medium"
            />

            <div class="px-3 py-1 col-span-3 flex flex-column justify-space-between">
              <div>
                {{ character.node.name.full }}
              </div>
              <div class="text-caption font-weight-light">
                {{ character.role }}
              </div>
            </div>
          </div>
          <v-slide-x-transition>
            <div
              v-if="character.voiceActors[0]?.name"
              class="grid grid-cols-4"
            >
              <div class="px-3 py-1 col-span-3 text-right flex flex-column justify-space-between">
                <div>
                  {{ character.voiceActors[0].name.full }}
                </div>
                <div class="font-weight-light">
                  Japanese
                </div>
              </div>
              <v-img
                :src="character.voiceActors[0].image.large"
                :lazy-src="character.voiceActors[0].image.medium"
              />
            </div>
          </v-slide-x-transition>
        </div>
      </v-card>
    </div>
  </div>
</template>

<style scoped>

</style>

// resources/js/components/anime/casts.svelte
<script lang="ts">
    type CharacterEdge = App.Data.Anilist.CharacterEdgeData;

    type Props = {
        characters: CharacterEdge[];
    };

    let { characters }: Props = $props();
</script>

<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
    {#each characters as character (character.node?.id)}
        <div
            class="grid grid-cols-2 overflow-hidden rounded-none bg-muted/50 md:rounded-lg"
        >
            <div class="grid grid-cols-4">
                <img
                    src={character.node?.image?.large ?? undefined}
                    alt={character.node?.name?.full ?? ''}
                    class="aspect-2/3 w-full object-cover"
                />
                <div class="col-span-3 flex flex-col justify-between px-3 py-2">
                    <div class="text-sm font-medium">
                        {character.node?.name?.full}
                    </div>
                    <div class="text-muted-foreground text-xs">
                        {character.role}
                    </div>
                </div>
            </div>
            {#if character.voiceActors?.[0]?.name}
                <div class="grid grid-cols-4">
                    <div
                        class="col-span-3 flex flex-col justify-between px-3 py-2 text-right"
                    >
                        <div class="text-sm font-medium">
                            {character.voiceActors[0].name.full}
                        </div>
                        <div class="text-muted-foreground text-xs">
                            Japanese
                        </div>
                    </div>
                    <img
                        src={character.voiceActors[0].image?.large ?? undefined}
                        alt={character.voiceActors[0].name.full}
                        class="aspect-2/3 w-full object-cover"
                    />
                </div>
            {/if}
        </div>
    {/each}
</div>
