// resources/js/Pages/Anime/Post/Create.vue
<script lang="ts" setup>

import { AnimeData, EpisodeData, Resource } from '@/types/anime'
import { Head, router, useForm } from '@inertiajs/vue3'
import {
  mdiChevronDown,
  mdiChevronUp,
  mdiContentSave,
  mdiDelete,
  mdiOpenInNew,
  mdiPencil,
  mdiPlus,
  mdiSend,
} from 'mdi-js-es'
import PageHeader from '@/Layouts/Partials/PageHeader.vue'
import { useDisplay } from 'vuetify'
import { TranslatableField } from '@/types/formHelper'
import { useLanguages } from '@/composables/useLanguages'
import Metadata from '@/Pages/Anime/Partials/Metadata.vue'
import { computed, inject, ref } from 'vue'
import { route as ziggyRoute } from 'ziggy-js'
import { openConfirmationDialog, openFormDialog } from '@/composables/useDialog'
import MediaManager from '@/Components/MediaManager/Index.vue'
import { Media } from '@/types'
import AppLayout from '@/Layouts/AppLayout.vue'
import InertiaLink from '@/Components/InertiaLink'

defineOptions({
  name: 'AnimePostCreate',
  layout: AppLayout,
})

const props = defineProps<{
  anime: AnimeData
  canPublish: boolean
  post?: EpisodeData & {
    links: Resource[]
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    metadata: Record<string, any>
    thumbnail_item: Media | null
  }
}>()
const route = inject('route') as typeof ziggyRoute
const { mdAndUp } = useDisplay()
type PostForm = {
  title: TranslatableField
  description: TranslatableField
  is_published: boolean
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  metadata: Record<string, any>
  links: Resource[]
  thumbnail_item: Media | null
}

const form = useForm<PostForm>({
  title: {
    en: null,
    id: null,
    native: null,
    romaji: null,
  },
  is_published: true,
  description: {
    en: null,
    id: null,
  },
  metadata: {
    post_type: 'tv',
  },
  links: [],
  thumbnail_item: null,
},
)

if (props.post) {
  form.title = props.post.title
  form.description = props.post.description
  form.links = props.post.links
  form.metadata = props.post.metadata
  form.thumbnail_item = props.post.thumbnail_item
}

const submit = () => {
  if (props.post) {
    form.is_published = props.post.is_published
    form.put(route('post.update', [props.anime, props.post]))
  } else {
    form.post(route('post.store', props.anime))
  }
}
const save = () => {
  form.is_published = false
  submit()
}

const { smAndUp } = useDisplay()

const { languages, selectedLanguage: currentLang } = useLanguages()

const addFilename = async () => {
  try {
    const result = await openFormDialog('Tambahkan File')
    form.links.push({
      name: result,
      value: [{
        name: '',
        value: '',
      }],
      type: 'link',
    })
  } catch {
    //
  }
}

const addLink = (index: number) => {
  form.links[index].value.push({
    name: '',
    value: '',
  })
}

const editFilename = async (index: number) => {
  try {
    form.links[index].name = await openFormDialog('Edit filename', undefined, {
      label: 'Filename',
      variant: 'outlined',
      placeholder: form.links[index].name,
    })
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  } catch (e) { /* empty */
  }
}

const deleteFilename = (index: number) => {
  form.links.splice(index, 1)
}

const deleteLink = (i: number, j: number) => {
  form.links[i].value.splice(j, 1)
}

const { translate } = useLanguages()

const title = props.post ? 'Editing ' + translate(props.post?.title) : 'Create Episode'

const deletePost = async () => {
  try {
    const confirmed = await openConfirmationDialog('Are you sure want to delete this item?')
    if (confirmed && props.post?.id && props.anime.id) {
      router.delete(route('post.destroy', [props.anime.id, props.post.id]))
    }
  } catch {
    //
  }
}

const postType = [
  {
    value: 'bd',
    title: 'Blu-ray BOX/DISC',
  },
  {
    value: 'tv',
    title: 'TV Ep',
  },
  {
    value: 'movie',
    title: 'Movie',
  },
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const formErrors = computed(() => form.errors as any)

const showAnimeImage = ref(false)

</script>

<template>
  <Head :title />
  <PageHeader :title>
    <template #append>
      <div class="flex gap-2">
        <v-btn
          variant="outlined"
          color="error"
          :icon="!mdAndUp ? mdiDelete : undefined"
          :prepend-icon="mdAndUp ? mdiDelete : undefined"
          :text="mdAndUp ? 'Delete' : undefined"
          @click="deletePost"
        />
        <v-btn
          :variant="post?.is_published ? undefined : 'outlined'"
          :type="canPublish && !form.is_published? undefined : 'submit'"
          form="storePost"
          :disabled="form.processing"
          :color="post?.is_published ? 'primary' : 'secondary'"
          :icon="!mdAndUp ? mdiContentSave : undefined"
          :prepend-icon="mdAndUp ? mdiContentSave : undefined"
          :text="mdAndUp ? 'Save' : undefined"
          @click.prevent="save"
        />
        <v-btn
          v-if="canPublish && !post?.is_published"
          form="storePost"
          type="submit"
          :disabled="form.processing"
          color="primary"
          :icon="!mdAndUp ? mdiSend : undefined"
          :prepend-icon="mdAndUp ? mdiSend : undefined"
          :text="mdAndUp ? 'Publish' : undefined"
        />
      </div>
    </template>
  </PageHeader>
  <v-container class="p-0 p-sm-4">
    <v-form
      id="storePost"
      :disabled="form.processing"
      @submit.prevent="submit"
    >
      <div class="grid gap-4 grid-cols-1 md:grid-cols-12">
        <div class="md:col-span-8">
          <section class="mb-4">
            <v-card :rounded="smAndUp">
              <v-card-item title="Basic Information" />
              <v-divider />
              <v-card-text>
                <div class="flex items-start mb-4 gap-4">
                  <v-text-field
                    v-model="form.metadata.ep_no"
                    variant="outlined"
                    :hide-details="true"
                    label="Ep No."
                    placeholder="1-4"
                    class="flex-none w-32"
                  />
                  <v-select
                    v-model="currentLang"
                    :multiple="false"
                    label="Title language"
                    return-object
                    variant="outlined"
                    :items="languages"
                    item-title="label"
                    :hide-details="true"
                    item-value="value"
                    class="flex-none w-36"
                  />
                  <v-select
                    v-model="form.metadata['post_type']"
                    :multiple="false"
                    label="Ep. type"
                    variant="outlined"
                    :items="postType"
                    hide-details="auto"
                    :error-messages="formErrors['metadata.post_type']"
                    class="flex-none w-36"
                  />
                </div>
                <v-text-field
                  v-model="form.title[currentLang.value]"
                  :label="`Title (${currentLang.value})`"
                  :error-messages="formErrors['title.' + currentLang]"
                  variant="outlined"
                  hide-details="auto"
                  class="mb-4"
                />
                <v-text-field
                  v-model="form.title.romaji"
                  label="Title Romaji"
                  :error-messages="formErrors['title.romaji']"
                  variant="outlined"
                  hide-details="auto"
                  class="mb-4"
                />
                <v-text-field
                  v-model="form.title.native"
                  label="Title Native"
                  :error-messages="formErrors['title.native']"
                  variant="outlined"
                  hide-details="auto"
                  class="mb-4"
                />
                <v-textarea
                  v-model="form.description[currentLang.value]"
                  :label="`Description (${currentLang.value})`"
                  :error-messages="form.errors.description"
                  variant="outlined"
                  hide-details="auto"
                  class="mb-4"
                />
              </v-card-text>
            </v-card>
          </section>
          <section>
            <v-card :rounded="smAndUp">
              <v-card-item>
                <v-card-title>
                  Links
                </v-card-title>
                <template #append>
                  <v-btn
                    color="primary"
                    :prepend-icon="mdiPlus"
                    @click.prevent="addFilename"
                  >
                    Add
                  </v-btn>
                </template>
              </v-card-item>
              <v-divider />
              <v-card-text class="flex gap-4 flex-col">
                <v-card
                  v-for="(resource, i) in form.links"
                  :key="i"
                  variant="outlined"
                >
                  <v-card-item>
                    <template #prepend>
                      <v-btn
                        variant="plain"
                        :icon="true"
                        density="comfortable"
                        color="secondary"
                        @click="editFilename(i)"
                      >
                        <v-icon
                          :icon="mdiPencil"
                          size="20"
                        />
                      </v-btn>

                      <v-btn
                        variant="plain"
                        :icon="true"
                        density="comfortable"
                        color="error"
                        @click="deleteFilename(i)"
                      >
                        <v-icon
                          :icon="mdiDelete"
                          size="20"
                        />
                      </v-btn>
                    </template>
                    <v-card-title>
                      {{ resource.name }}
                    </v-card-title>
                    <template #append>
                      <v-btn
                        variant="plain"
                        :icon="true"
                        density="comfortable"
                        :prepend-icon="mdiPlus"
                        color="primary"
                        @click.prevent="addLink(i)"
                      >
                        <v-icon
                          :icon="mdiPlus"
                          size="20"
                        />
                      </v-btn>
                    </template>
                  </v-card-item>
                  <template
                    v-for="(links, j) in resource.value"
                    :key="`link-${i}-${j}`"
                  >
                    <v-card-text>
                      <v-row no-gutters>
                        <v-col cols="3">
                          <div class="text-medium-emphasis mt-2">
                            Name
                          </div>
                        </v-col>
                        <v-col cols="9">
                          <v-text-field
                            v-model="form.links[i].value[j].name"
                            placeholder="Gudang"
                            variant="outlined"
                            hide-details="auto"
                            class="mb-4"
                          />
                        </v-col>
                      </v-row>
                      <v-row no-gutters>
                        <v-col cols="3">
                          <div class="text-medium-emphasis mt-2">
                            Link/Embed code
                          </div>
                        </v-col>
                        <v-col cols="9">
                          <v-textarea
                            v-model="form.links[i].value[j].value"
                            placeholder="https://gudang.extonan.id/"
                            rows="2"
                            variant="outlined"
                            hide-details="auto"
                          />

                          <v-btn
                            color="error mt-4"
                            @click.prevent="deleteLink(i,j)"
                          >
                            Delete
                          </v-btn>
                        </v-col>
                      </v-row>
                    </v-card-text>
                    <v-divider v-if="j < resource.value.length" />
                  </template>
                  <v-card-text v-if="resource.value.length < 1">
                    No data.
                  </v-card-text>
                </v-card>
                <!--  -->
                <template v-if="form.links.length < 1">
                  No data.
                </template>
              </v-card-text>
            </v-card>
          </section>
        </div>
        <div class="md:col-span-4">
          <div>
            <!--TODO-->
            <MediaManager
              v-model="form.thumbnail_item"
              class="mb-4"
              title="Media Thumbnail"
              :multiple="false"
            />
            <v-card :rounded="smAndUp">
              <v-expand-transition>
                <v-img
                  v-if="showAnimeImage"
                  :src="anime.metadata.coverImage.extraLarge"
                  :lazy-src="anime.metadata.coverImage.medium"
                />
              </v-expand-transition>
              <v-card-item>
                <v-card-title>
                  Anime
                </v-card-title>
                <template #append>
                  <v-tooltip text="Show image">
                    <template #activator="{props: propss}">
                      <v-btn
                        v-bind="propss"
                        variant="text"
                        :icon="showAnimeImage ? mdiChevronUp : mdiChevronDown"
                        @click="showAnimeImage = !showAnimeImage"
                      />
                    </template>
                  </v-tooltip>
                </template>
              </v-card-item>
              <v-divider />
              <v-card-text>
                <!-- template -->
                <div>
                  <v-list-subheader>
                    Title
                  </v-list-subheader>
                  <InertiaLink :href="route('anime.show', anime.id)">
                    {{ anime.title.en }}
                  </InertiaLink>
                </div>
                <div>
                  <v-list-subheader>
                    Links
                  </v-list-subheader>
                  <div class="flex gap-1">
                    <v-chip
                      prepend-avatar="https://upload.wikimedia.org/wikipedia/commons/6/61/AniList_logo.svg"
                      :href="`https://anilist.co/anime/${anime.metadata.id}`"
                      target="_blank"
                    >
                      Anilist
                      <v-icon :icon="mdiOpenInNew" />
                    </v-chip>
                    <v-chip
                      prepend-avatar="https://upload.wikimedia.org/wikipedia/commons/9/9b/MyAnimeList_favicon.svg"
                      :href="`https://myanimelist.net/anime/${anime.metadata.idMal}`"
                      target="_blank"
                    >
                      MyAnimelist
                      <v-icon :icon="mdiOpenInNew" />
                    </v-chip>
                  </div>
                </div>
              </v-card-text>

              <v-expand-transition>
                <div v-if="anime.metadata">
                  <v-divider />
                  <v-card-text>
                    <Metadata
                      :data="anime.metadata"
                    />
                  </v-card-text>
                </div>
              </v-expand-transition>
            </v-card>
          </div>
        </div>
      </div>
    </v-form>
  </v-container>
</template>

// resources/js/pages/anime/post/Create.svelte
<script module lang="ts">
    import { index as animeIndex } from '@/routes/anime';

    export const layout = {
        breadcrumbs: [
            { title: 'Anime', href: animeIndex().url },
            { title: 'Create Episode', href: '' },
        ],
    };
</script>

<script lang="ts">
    import { router, useForm } from '@inertiajs/svelte';
    import Check from 'lucide-svelte/icons/check';
    import ChevronDown from 'lucide-svelte/icons/chevron-down';
    import ChevronUp from 'lucide-svelte/icons/chevron-up';
    import ExternalLink from 'lucide-svelte/icons/external-link';
    import Pencil from 'lucide-svelte/icons/pencil';
    import Plus from 'lucide-svelte/icons/plus';
    import Send from 'lucide-svelte/icons/send';
    import Trash2 from 'lucide-svelte/icons/trash-2';
    import PostController from '@/actions/App/Http/Controllers/PostController';
    import AppHead from '@/components/app-head.svelte';
    import InputError from '@/components/input-error.svelte';
    import { Badge } from '@/components/ui/badge';
    import { Button } from '@/components/ui/button';
    import * as Card from '@/components/ui/card/index.js';
    import * as DropdownMenu from '@/components/ui/dropdown-menu/index.js';
    import { Input } from '@/components/ui/input';
    import * as InputGroup from '@/components/ui/input-group/index.js';
    import { Label } from '@/components/ui/label';
    import { Switch } from '@/components/ui/switch';
    import { Textarea } from '@/components/ui/textarea';
    import { useDisplay } from '@/lib/use-display.svelte';

    type PostFormData = App.Data.Anime.PostFormData;
    type AnilistMediaData = App.Data.Anilist.AnilistMediaData;

    type Props = App.Data.Anime.PostCreateResponse;

    let {
        anime,
        post = null,
        canPublish = false,
        metadata = null,
    }: Props = $props();

    const { mdAndDown } = useDisplay();
    const isMobile = $derived(mdAndDown.current);

    const isEditing = $derived(Boolean(post));
    const pageTitle = $derived(
        isEditing ? `Editing Episode` : 'Create Episode',
    );

    let currentLang = $state<'en' | 'id'>('en');
    let showAnimeImage = $state(false);

    const languages: { label: string; value: 'en' | 'id' }[] = [
        { label: 'English', value: 'en' },
        { label: 'Indonesian', value: 'id' },
    ];

    const postTypes = [
        { value: 'tv', label: 'TV Ep' },
        { value: 'bd', label: 'Blu-ray BOX/DISC' },
        { value: 'movie', label: 'Movie' },
    ];

    const form = $state(
        useForm<PostFormData>({
            title: post?.title ?? { en: '', id: '', romaji: '', native: '' },
            description: post?.description ?? { en: '', id: '' },
            postType: post?.postType ?? 'tv',
            epNo: post?.epNo ?? '',
            isPublished: post?.isPublished ?? false,
            links: post?.links ?? [],
            thumbnailItem: post?.thumbnailItem ?? null,
        }),
    );

    const title = $derived(
        isEditing
            ? `Editing ${post?.epNo ? 'Ep ' + post.epNo : 'Episode'}`
            : 'Create Episode',
    );

    function submit(e: Event) {
        e.preventDefault();

        if (isEditing && post?.id) {
            form.put(PostController.update(anime.id, post.id).url, {
                preserveScroll: true,
            });
        } else {
            form.post(PostController.store(anime.id).url);
        }
    }

    function publish() {
        form.isPublished = true;
        submit(new Event('submit'));
    }

    function save() {
        submit(new Event('submit'));
    }

    function deletePost() {
        if (!post?.id) {
            return;
        }

        if (confirm('Are you sure you want to delete this episode?')) {
            router.delete(PostController.destroy(anime.id, post.id).url);
        }
    }

    function addFilename() {
        const name = window.prompt('Enter filename');

        if (name) {
            form.links = [
                ...form.links,
                { name, type: 'link', value: [{ name: '', value: '' }] },
            ];
        }
    }

    function editFilename(index: number) {
        const name = window.prompt('Edit filename', form.links[index].name);

        if (name !== null) {
            form.links[index].name = name;
        }
    }

    function deleteFilename(index: number) {
        form.links = form.links.filter((_, i) => i !== index);
    }

    function addLink(index: number) {
        form.links[index].value = [
            ...form.links[index].value,
            { name: '', value: '' },
        ];
    }

    function deleteLink(i: number, j: number) {
        form.links[i].value = form.links[i].value.filter((_, k) => k !== j);
    }
</script>

<AppHead title={pageTitle} />

<div class="p-4 w-full mx-auto max-w-400">
    <form onsubmit={submit}>
        <div class="grid gap-4 md:gap-6 md:grid-cols-12">
            <div class="space-y-6 md:col-span-8">
                <Card.Root>
                    <Card.Content class="space-y-4">
                        <Card.Title>Basic Information</Card.Title>

                        <div class="flex items-start gap-4">
                            <div class="flex-none w-32">
                                <Label for="ep_no">Ep No.</Label>
                                <Input
                                    id="ep_no"
                                    bind:value={form.epNo}
                                    placeholder="1-4"
                                />
                            </div>

                            <div class="flex-none w-36">
                                <Label>Title Language</Label>
                                <DropdownMenu.Root>
                                    <DropdownMenu.Trigger>
                                        {#snippet child({
                                            props: triggerProps,
                                        })}
                                            <Button
                                                variant="outline"
                                                class="w-full justify-between"
                                                {...triggerProps}
                                            >
                                                {languages.find(
                                                    (l) =>
                                                        l.value === currentLang,
                                                )?.label ?? 'Language'}
                                                <ChevronDown
                                                    class="size-4 opacity-50"
                                                />
                                            </Button>
                                        {/snippet}
                                    </DropdownMenu.Trigger>
                                    <DropdownMenu.Content>
                                        {#each languages as lang (lang.value)}
                                            <DropdownMenu.Item
                                                onclick={() =>
                                                    (currentLang = lang.value)}
                                            >
                                                <div
                                                    class="flex w-full items-center gap-2"
                                                >
                                                    {#if currentLang === lang.value}
                                                        <Check class="size-4" />
                                                    {/if}
                                                    <span>{lang.label}</span>
                                                </div>
                                            </DropdownMenu.Item>
                                        {/each}
                                    </DropdownMenu.Content>
                                </DropdownMenu.Root>
                            </div>

                            <div class="flex-none w-36">
                                <Label>Ep. Type</Label>
                                <DropdownMenu.Root>
                                    <DropdownMenu.Trigger>
                                        {#snippet child({
                                            props: triggerProps,
                                        })}
                                            <Button
                                                variant="outline"
                                                class="w-full justify-between"
                                                {...triggerProps}
                                            >
                                                {postTypes.find(
                                                    (t) =>
                                                        t.value ===
                                                        form.postType,
                                                )?.label ?? 'Type'}
                                                <ChevronDown
                                                    class="size-4 opacity-50"
                                                />
                                            </Button>
                                        {/snippet}
                                    </DropdownMenu.Trigger>
                                    <DropdownMenu.Content>
                                        {#each postTypes as type (type.value)}
                                            <DropdownMenu.Item
                                                onclick={() =>
                                                    (form.postType =
                                                        type.value)}
                                            >
                                                <div
                                                    class="flex w-full items-center gap-2"
                                                >
                                                    {#if form.postType === type.value}
                                                        <Check class="size-4" />
                                                    {/if}
                                                    <span>{type.label}</span>
                                                </div>
                                            </DropdownMenu.Item>
                                        {/each}
                                    </DropdownMenu.Content>
                                </DropdownMenu.Root>
                            </div>
                        </div>

                        <div class="grid gap-2">
                            <Label for="title_lang">
                                Title ({currentLang})
                            </Label>
                            <Input
                                id="title_lang"
                                bind:value={form.title[currentLang]}
                                placeholder={`Title in ${languages.find((l) => l.value === currentLang)?.label}`}
                            />
                            <InputError
                                message={form.errors[`title.${currentLang}`]}
                            />
                        </div>

                        <div class="grid gap-2">
                            <Label for="title_romaji">Title (Romaji)</Label>
                            <Input
                                id="title_romaji"
                                bind:value={form.title.romaji}
                                placeholder="Title in romaji"
                            />
                            <InputError message={form.errors['title.romaji']} />
                        </div>

                        <div class="grid gap-2">
                            <Label for="title_native">Title (Native)</Label>
                            <Input
                                id="title_native"
                                bind:value={form.title.native}
                                placeholder="Title in native script"
                            />
                            <InputError message={form.errors['title.native']} />
                        </div>

                        <div class="grid gap-2">
                            <Label for="description_lang">
                                Description ({currentLang})
                            </Label>
                            <Textarea
                                id="description_lang"
                                bind:value={form.description[currentLang]}
                                rows={6}
                                placeholder={`Description in ${languages.find((l) => l.value === currentLang)?.label}`}
                            />
                            <InputError
                                message={form.errors[
                                    `description.${currentLang}`
                                ]}
                            />
                        </div>
                    </Card.Content>
                </Card.Root>

                <Card.Root>
                    <Card.Header
                        class="flex flex-row items-center justify-between"
                    >
                        <Card.Title>Links</Card.Title>
                        <Button
                            variant="outline"
                            size="sm"
                            onclick={addFilename}
                        >
                            <Plus class="mr-1 size-4" />
                            Add
                        </Button>
                    </Card.Header>
                    <Card.Content class="flex flex-col gap-4">
                        {#each form.links as resource, i (i)}
                            <Card.Root variant="outlined">
                                <Card.Header
                                    class="flex flex-row items-center justify-between py-2"
                                >
                                    <div class="flex items-center gap-2">
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            class="size-8"
                                            onclick={() => editFilename(i)}
                                        >
                                            <Pencil class="size-4" />
                                        </Button>
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            class="size-8 text-destructive"
                                            onclick={() => deleteFilename(i)}
                                        >
                                            <Trash2 class="size-4" />
                                        </Button>
                                        <Card.Title class="text-sm">
                                            {resource.name}
                                        </Card.Title>
                                    </div>
                                    <Button
                                        variant="ghost"
                                        size="icon"
                                        class="size-8"
                                        onclick={() => addLink(i)}
                                    >
                                        <Plus class="size-4" />
                                    </Button>
                                </Card.Header>
                                <Card.Content class="pt-0">
                                    {#if resource.value.length === 0}
                                        <p
                                            class="text-sm text-muted-foreground"
                                        >
                                            No data.
                                        </p>
                                    {:else}
                                        {#each resource.value as link, j (j)}
                                            <div
                                                class="grid grid-cols-[80px_1fr] gap-2 items-start mb-2"
                                            >
                                                <Label
                                                    class="mt-2 text-muted-foreground"
                                                >
                                                    Name
                                                </Label>
                                                <Input
                                                    bind:value={
                                                        form.links[i].value[j]
                                                            .name
                                                    }
                                                    placeholder="Gudang"
                                                />
                                            </div>
                                            <div
                                                class="grid grid-cols-[80px_1fr] gap-2 items-start mb-2"
                                            >
                                                <Label
                                                    class="mt-2 text-muted-foreground"
                                                >
                                                    Link
                                                </Label>
                                                <div class="space-y-2">
                                                    <Textarea
                                                        bind:value={
                                                            form.links[i].value[
                                                                j
                                                            ].value
                                                        }
                                                        placeholder="https://..."
                                                        rows={2}
                                                    />
                                                    <Button
                                                        variant="destructive"
                                                        size="sm"
                                                        onclick={() =>
                                                            deleteLink(i, j)}
                                                    >
                                                        Delete
                                                    </Button>
                                                </div>
                                            </div>
                                        {/each}
                                    {/if}
                                </Card.Content>
                            </Card.Root>
                        {/each}

                        {#if form.links.length === 0}
                            <p class="text-sm text-muted-foreground">
                                No data.
                            </p>
                        {/if}
                    </Card.Content>
                </Card.Root>
            </div>

            <div
                class="space-y-6 md:col-span-4 md:sticky md:top-4 md:self-start"
            >
                <Card.Root>
                    <Card.Header
                        class="flex flex-row items-center justify-between"
                    >
                        <Card.Title>Anime</Card.Title>
                        <Button
                            variant="ghost"
                            size="icon"
                            class="size-8"
                            onclick={() => (showAnimeImage = !showAnimeImage)}
                        >
                            {#if showAnimeImage}
                                <ChevronUp class="size-4" />
                            {:else}
                                <ChevronDown class="size-4" />
                            {/if}
                        </Button>
                    </Card.Header>
                    {#if showAnimeImage && metadata?.coverImage?.extraLarge}
                        <div class="px-6">
                            <img
                                src={metadata.coverImage.extraLarge}
                                alt="Cover"
                                class="w-full rounded-lg object-cover"
                            />
                        </div>
                    {/if}
                    <Card.Content class="space-y-4">
                        <div>
                            <p class="text-sm font-medium leading-none mb-1">
                                Title
                            </p>
                            <a
                                href="/anime/{anime.id}"
                                class="text-sm text-primary underline-offset-4 hover:underline"
                            >
                                {anime.title.en}
                            </a>
                        </div>
                        <div>
                            <p class="text-sm font-medium leading-none mb-2">
                                Links
                            </p>
                            <div class="flex gap-1">
                                {#if metadata?.id}
                                    <a
                                        href="https://anilist.co/anime/{metadata.id}"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                    >
                                        <Badge variant="secondary">
                                            Anilist
                                            <ExternalLink class="ml-1 size-3" />
                                        </Badge>
                                    </a>
                                {/if}
                                {#if metadata?.idMal}
                                    <a
                                        href="https://myanimelist.net/anime/{metadata.idMal}"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                    >
                                        <Badge variant="secondary">
                                            MyAnimelist
                                            <ExternalLink class="ml-1 size-3" />
                                        </Badge>
                                    </a>
                                {/if}
                            </div>
                        </div>
                    </Card.Content>
                </Card.Root>

                <Card.Root>
                    <Card.Content class="space-y-4">
                        <Card.Title>Publishing</Card.Title>
                        <div class="flex items-center gap-2">
                            <Switch
                                checked={form.isPublished}
                                onCheckedChange={(v) => (form.isPublished = v)}
                                id="is_published"
                            />
                            <Label for="is_published">Published</Label>
                        </div>
                        <InputError message={form.errors.isPublished} />
                    </Card.Content>
                </Card.Root>

                <div class="flex gap-2">
                    {#if isEditing}
                        <Button
                            type="button"
                            variant="destructive"
                            size="icon"
                            onclick={deletePost}
                            disabled={form.processing}
                        >
                            <Trash2 class="size-4" />
                        </Button>
                    {/if}
                    <Button
                        type="button"
                        variant="outline"
                        onclick={() => form.reset()}
                        disabled={form.processing}
                    >
                        Reset
                    </Button>
                    <Button
                        type="button"
                        variant={post?.isPublished ? 'default' : 'outline'}
                        onclick={save}
                        disabled={form.processing}
                        class="flex-1"
                    >
                        {form.processing
                            ? 'Saving...'
                            : isEditing
                              ? 'Update'
                              : 'Save'}
                    </Button>
                    {#if canPublish && !post?.isPublished}
                        <Button
                            type="button"
                            onclick={publish}
                            disabled={form.processing}
                            class="flex-1"
                        >
                            {form.processing ? 'Publishing...' : 'Publish'}
                        </Button>
                    {/if}
                </div>
            </div>
        </div>
    </form>
</div>
