// resources/js/pages/auth/ConfirmPassword.svelte
<script module lang="ts">
    export const layout = {
        title: 'Confirm password',
        description:
            'This is a secure area of the application. Please confirm your password before continuing.',
    };
</script>

<script lang="ts">
    import { Form } from '@inertiajs/svelte';
    import {
        index as confirmOptions,
        store as confirmStore,
    } from '@/actions/Laravel/Passkeys/Http/Controllers/PasskeyConfirmationController';
    import AppHead from '@/components/app-head.svelte';
    import InputError from '@/components/input-error.svelte';
    import PasswordInput from '@/components/password-input.svelte';
    import { Button } from '@/components/ui/button';
    import { Label } from '@/components/ui/label';
    import { Spinner } from '@/components/ui/spinner';
    import { store } from '@/routes/password/confirm';
    import PasskeyVerify from './components/passkey-verify.svelte';
</script>

<AppHead title="Confirm password" />

<PasskeyVerify
    routes={{
        options: confirmOptions(),
        submit: confirmStore(),
    }}
    label="Confirm with passkey"
    loadingLabel="Confirming..."
    separator="Or confirm with password"
/>

<Form {...store.form()} resetOnSuccess>
    {#snippet children({ errors, processing })}
        <div class="space-y-6">
            <div class="grid gap-2">
                <Label for="password">Password</Label>
                <PasswordInput
                    id="password"
                    name="password"
                    class="mt-1 block w-full"
                    required
                    autocomplete="current-password"
                />
                <InputError message={errors.password} />
            </div>

            <div class="flex items-center">
                <Button
                    type="submit"
                    class="w-full"
                    disabled={processing}
                    data-test="confirm-password-button"
                >
                    {#if processing}<Spinner />{/if}
                    Confirm password
                </Button>
            </div>
        </div>
    {/snippet}
</Form>

// resources/js/Pages/Auth/ConfirmPassword.vue
<template>
  <div>
    Card de autenticacion con solo la password bb
    <!-- <jet-authentication-card>
        <template #logo>
            <jet-authentication-card-logo />
        </template>

        <div class="mb-4 text-sm text-gray-600">
            This is a secure area of the application. Please confirm your password before continuing.
        </div>

        <jet-validation-errors class="mb-4" />

        <form @submit.prevent="submit">
            <div>
                <jet-label for="password" value="Password" />
                <jet-input id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="current-password" autofocus />
            </div>

            <div class="flex justify-end mt-4">
                <jet-button class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Confirm
                </jet-button>
            </div>
        </form>
        </jet-authentication-card> -->
  </div>
</template>

<script>
// import JetAuthenticationCard from '@/Jetstream/AuthenticationCard'
// import JetAuthenticationCardLogo from '@/Jetstream/AuthenticationCardLogo'
// import JetButton from '@/Jetstream/Button'
// import JetInput from '@/Jetstream/Input'
// import JetLabel from '@/Jetstream/Label'
// import JetValidationErrors from '@/Jetstream/ValidationErrors'

export default {
  components: {
    // JetAuthenticationCard,
    // JetAuthenticationCardLogo,
    // JetButton,
    // JetInput,
    // JetLabel,
    // JetValidationErrors
  },

  data () {
    return {
      form: this.$inertia.form({
        password: ''
      })
    }
  },

  methods: {
    submit () {
      this.form.post(this.route('password.confirm'), {
        onFinish: () => this.form.reset()
      })
    }
  }
}
</script>
