// resources/js/vue/Pages/Auth/Login.vue
<script setup lang="ts">
import { Head, useForm, usePage } from '@inertiajs/vue3'
import Socialstream from '@/Components/Socialstream.vue'

import { Socialstream as SocialstreamType } from '@/types'

import AuthLayout from '@/Layouts/AuthLayout.vue'
import { Link } from '@inertiajs/vue3'
import { VBtn } from 'vuetify/components'
import { mdiEye, mdiEyeOff } from 'mdi-js-es'
import { inject, ref } from 'vue'
import { route as ziggyRoute } from 'ziggy-js'

defineProps<{
  canResetPassword: boolean
  status?: string
  socialstream: SocialstreamType
}>()

const inertiaProps = usePage().props

const route = inject('route') as typeof ziggyRoute

// const route = inject(ziggySymbol)!

const form = useForm({
  email: '',
  password: '',
  remember: false,
})

const showP = ref(false)

const submit = () => {
  form.transform(data => ({
    ...data,
    remember: form.remember ? 'on' : '',
  })).post(route('login'), {
    onFinish: () => form.reset('password'),
  })
}

</script>

<template>
  <Head title="Log in" />
  <AuthLayout>
    <Link
      :as="VBtn"
      href="/"
      flat
      icon
      size="100"
      class="mb-4"
    >
      <v-avatar
        color="grey darken-1"
        size="100"
      />
    </Link>

    <v-card
      width="100%"
      max-width="400px"
    >
      <v-card-text>
        <v-form
          class="mx-auto"
          :disabled="form.processing"
          @submit.prevent="submit"
        >
          <h2 class="text-h4 mb-4">
            Welcome Back!
          </h2>
          <v-alert
            v-if="$page.props.canRegister"
            density="comfortable"
            type="info"
            variant="tonal"
            class="mb-4"
          >
            Don't have an account?
            <Link
              :href="route('register')"
              class="text-info"
            >
              Sign up
            </Link>
          </v-alert>
          <p
            v-if="status"
            class="text-success mb-4"
          >
            {{ status }}
          </p>
          <p
            v-else
            class="mb-4"
          >
            Please sign-in to your account
          </p>
          <v-text-field
            v-model="form.email"
            variant="outlined"
            label="Email Address"
            :error-messages="form.errors.email"
            placeholder="john@example.com"
            required
            autofocus
            hide-details="auto"
            class="mb-4"
          />
          <v-text-field
            v-model="form.password"
            variant="outlined"
            label="Password"
            placeholder="************"
            required
            autocomplete="current-password"
            :error-messages="form.errors.password"
            :append-inner-icon="showP ? mdiEye : mdiEyeOff"
            :type="showP ? 'text' : 'password'"
            class="mb-4"
            hide-details="auto"
            @click:append-inner="showP = !showP"
          />
          <v-checkbox
            v-model="form.remember"
            hide-details="auto"
            label="Remember me"
          />
          <div
            class="flex align-center gap-4"
          >
            <Link
              v-if="canResetPassword"
              :href="route('password.request')"
            >
              Forgot your password?
            </Link>
            <v-spacer />
            <v-btn
              color="primary"
              type="submit"
              :disabled="form.processing"
            >
              Sign In
            </v-btn>
          </div>
        </v-form>
        <Socialstream
          v-if="socialstream?.show && socialstream.providers.length"
          :error="inertiaProps.errors.socialstream"
          :prompt="socialstream.prompt"
          :providers="socialstream.providers"
        />
      </v-card-text>
    </v-card>
  </AuthLayout>
</template>

// resources/js/pages/auth/Login.svelte
<script lang="ts">
    import InputError from '@/components/InputError.svelte';
    import TextLink from '@/components/typography/TextLink.svelte';
    import { Button } from '@/components/ui/button';
    import { Checkbox } from '@/components/ui/checkbox';
    import { Input } from '@/components/ui/input';
    import { Label } from '@/components/ui/label';
    import { Spinner } from '@/components/ui/spinner';
    import AuthBase from '@/layouts/AuthLayout.svelte';
    import type { BaseFormSnippetProps } from '@/types/forms';
    import { Form } from '@inertiajs/svelte';

    interface Props {
        status?: string;
        canResetPassword: boolean;
        canRegister: boolean;
    }

    let { status, canResetPassword, canRegister }: Props = $props();
</script>

<svelte:head>
    <title>Login</title>
</svelte:head>

<AuthBase title="Log in to your account" description="Enter your email and password below to log in">
    {#if status}
        <div class="mb-4 text-center text-sm font-medium text-green-600">
            {status}
        </div>
    {/if}

    <Form method="post" action={route('login')} resetOnSuccess={['password']} class="flex flex-col gap-6">
        {#snippet children({ errors, processing }: BaseFormSnippetProps)}
            <div class="grid gap-6">
                <div class="grid gap-2">
                    <Label for="email">Email address</Label>
                    <Input
                        id="email"
                        name="email"
                        type="email"
                        required
                        autofocus
                        tabindex={1}
                        autocomplete="email"
                        placeholder="email@example.com"
                    />
                    <InputError message={errors.email} />
                </div>

                <div class="grid gap-2">
                    <div class="flex items-center justify-between">
                        <Label for="password">Password</Label>
                        {#if canResetPassword}
                            <TextLink href={route('password.request')} class="text-sm" tabindex={5}>Forgot password?</TextLink>
                        {/if}
                    </div>
                    <Input
                        id="password"
                        name="password"
                        type="password"
                        required
                        tabindex={2}
                        autocomplete="current-password"
                        placeholder="Password"
                    />
                    <InputError message={errors.password} />
                </div>

                <div class="flex items-center justify-between">
                    <Label for="remember" class="flex items-center space-x-3">
                        <Checkbox id="remember" name="remember" tabindex={3} />
                        <span>Remember me</span>
                    </Label>
                </div>

                <Button type="submit" class="mt-4 w-full" tabindex={4} disabled={processing}>
                    {#if processing}
                        <Spinner />
                    {/if}
                    Log in
                </Button>
            </div>

            {#if canRegister}
                <div class="text-center text-sm text-muted-foreground">
                    Don't have an account?
                    <TextLink href={route('register')} tabindex={5}>Sign up</TextLink>
                </div>
            {/if}
        {/snippet}
    </Form>
</AuthBase>
