// resources/js/pages/auth/Login.svelte
<script lang="ts">
    import InputError from '@/components/InputError.svelte';
    import TextLink from '@/components/typography/TextLink.svelte';
    import { Button } from '@/components/ui/button';
    import { Checkbox } from '@/components/ui/checkbox';
    import { Input } from '@/components/ui/input';
    import { Label } from '@/components/ui/label';
    import { Spinner } from '@/components/ui/spinner';
    import AuthBase from '@/layouts/AuthLayout.svelte';
    import type { BaseFormSnippetProps } from '@/types/forms';
    import { Form } from '@inertiajs/svelte';

    interface Props {
        status?: string;
        canResetPassword: boolean;
        canRegister: boolean;
    }

    let { status, canResetPassword, canRegister }: Props = $props();
</script>

<svelte:head>
    <title>Login</title>
</svelte:head>

<AuthBase title="Log in to your account" description="Enter your email and password below to log in">
    {#if status}
        <div class="mb-4 text-center text-sm font-medium text-green-600">
            {status}
        </div>
    {/if}

    <Form method="post" action={route('login')} resetOnSuccess={['password']} class="flex flex-col gap-6">
        {#snippet children({ errors, processing }: BaseFormSnippetProps)}
            <div class="grid gap-6">
                <div class="grid gap-2">
                    <Label for="email">Email address</Label>
                    <Input
                        id="email"
                        name="email"
                        type="email"
                        required
                        autofocus
                        tabindex={1}
                        autocomplete="email"
                        placeholder="email@example.com"
                    />
                    <InputError message={errors.email} />
                </div>

                <div class="grid gap-2">
                    <div class="flex items-center justify-between">
                        <Label for="password">Password</Label>
                        {#if canResetPassword}
                            <TextLink href={route('password.request')} class="text-sm" tabindex={5}>Forgot password?</TextLink>
                        {/if}
                    </div>
                    <Input
                        id="password"
                        name="password"
                        type="password"
                        required
                        tabindex={2}
                        autocomplete="current-password"
                        placeholder="Password"
                    />
                    <InputError message={errors.password} />
                </div>

                <div class="flex items-center justify-between">
                    <Label for="remember" class="flex items-center space-x-3">
                        <Checkbox id="remember" name="remember" tabindex={3} />
                        <span>Remember me</span>
                    </Label>
                </div>

                <Button type="submit" class="mt-4 w-full" tabindex={4} disabled={processing}>
                    {#if processing}
                        <Spinner />
                    {/if}
                    Log in
                </Button>
            </div>

            {#if canRegister}
                <div class="text-center text-sm text-muted-foreground">
                    Don't have an account?
                    <TextLink href={route('register')} tabindex={5}>Sign up</TextLink>
                </div>
            {/if}
        {/snippet}
    </Form>
</AuthBase>

// resources/js/Pages/Auth/Login.vue
<template>
  <web-layout>
    <v-row justify="center">
      <v-col
        cols="10"
        sm="8"
        md="6"
      >
        <v-card>
          <v-card-title>Sign in to your account</v-card-title>
          <v-card-text>
            <validation-errors class="mb-4" />

            <div
              v-if="status"
              class="mb-4 font-medium text-sm text-green-600"
            >
              {{ status }}
            </div>

            <form @submit.prevent="submit">
              <v-text-field
                v-model="form.email"
                dense
                outlined
                label="Email Address"
                required
                autofocus
              />
              <v-text-field
                v-model="form.password"
                dense
                outlined
                label="Password"
                required
                autocomplete="current-password"
                :append-icon="showP ? 'mdi-eye' : 'mdi-eye-off'"
                :type="showP ? 'text' : 'password'"
                hint="At least 8 characters"
                @click:append="showP = !showP"
              />
              <v-checkbox
                v-model="form.remember"
                label="Remember me"
              />
              <v-btn
                block
                color="primary"
                type="submit"
                :disabled="form.processing"
              >
                Sign In
              </v-btn>
            </form>

            <socialstream-providers v-if="$page.props.socialstream.show" />

            <div class="mt-4 d-flex justify-space-between text-body-1">
              <inertia-link
                v-if="canResetPassword"
                :href="route('password.request')"
              >
                Forgot your password?
              </inertia-link>

              <div>
                Don't have an account?
                <inertia-link :href="route('register')">
                  Sign up
                </inertia-link>
              </div>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
    <v-sheet
      class=""
      color="gray pulse"
      width="200px"
    />
  </web-layout>
</template>

<script>
import ValidationErrors from '@/Components/ValidationErrors'
import WebLayout from '@/Layouts/Web/Index.vue'
import SocialstreamProviders from '@/Socialstream/Providers.vue'

export default {
  components: {
    ValidationErrors,
    // eslint-disable-next-line vue/no-unused-components
    SocialstreamProviders,
    WebLayout
  },

  props: {
    canResetPassword: Boolean,
    // eslint-disable-next-line vue/require-default-prop
    status: String
  },

  data () {
    return {
      form: this.$inertia.form({
        email: '',
        password: '',
        remember: false
      }),
      showP: false
    }
  },

  methods: {
    submit () {
      this.form
        .transform(data => ({
          ...data,
          remember: this.form.remember ? 'on' : ''
        }))
        .post(this.route('login'), {
          onFinish: () => this.form.reset('password')
        })
    }
  }
}
</script>
