// resources/js/pages/auth/VerifyEmail.svelte
<script lang="ts">
    import TextLink from '@/components/typography/TextLink.svelte';
    import { Button } from '@/components/ui/button';
    import AuthLayout from '@/layouts/AuthLayout.svelte';
    import { Form } from '@inertiajs/svelte';
    import { LoaderCircle } from 'lucide-svelte';

    interface Props {
        status?: string;
    }

    let { status }: Props = $props();
</script>

<svelte:head>
    <title>Verify Email</title>
</svelte:head>

<AuthLayout title="Verify email" description="Please verify your email address by clicking on the link we just emailed to you.">
    {#if status === 'verification-link-sent'}
        <div class="mb-4 text-center text-sm font-medium text-green-600">
            A new verification link has been sent to the email address you provided during registration.
        </div>
    {/if}

    <Form method="post" action={route('verification.send')} className="space-y-6 text-center">
        {#snippet children({ processing }: { processing: boolean })}
            <Button type="submit" disabled={processing} variant="secondary">
                {#if processing}
                    <LoaderCircle class="h-4 w-4 animate-spin" />
                {/if}
                Resend verification email
            </Button>

            <TextLink href={route('logout')} method="post" as="button" class="mx-auto block text-sm">Log out</TextLink>
        {/snippet}
    </Form>
</AuthLayout>

// resources/js/Pages/Auth/VerifyEmail.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Head, useForm } from '@inertiajs/vue3'
import { VBtn } from 'vuetify/components'
import AuthLayout from '@/Layouts/AuthLayout.vue'
import InertiaLink from '@/Components/InertiaLink.vue'

const props = defineProps<{
  status: string
}>()

const form = useForm({})

const submit = () => {
  form.post(route('verification.send'))
}

const verificationLinkSent = computed(() => props.status === 'verification-link-sent')
</script>

<template>
  <Head title="Email Verification" />
  <AuthLayout>
    <InertiaLink
      :as="VBtn"
      href="/"
      flat
      icon
      size="100"
      class="mb-4"
    >
      <v-avatar
        color="grey darken-1"
        size="100"
      />
    </InertiaLink>
    <v-card
      width="100%"
      max-width="480px"
    >
      <v-form
        :disabled="form.processing"
        @submit.prevent="submit"
      >
        <v-card-text>
          <p class="mb-4">
            Before continuing, could you verify your email address by clicking on the link we just emailed to you? If
            you didn't receive the email, we will gladly send you another.
          </p>
          <v-scroll-x-transition>
            <p
              v-show="verificationLinkSent"
              class="mb-4 text-success"
            >
              A new verification link has been sent to the email address you provided in your profile settings.
            </p>
          </v-scroll-x-transition>

          <div
            class="d-flex align-center gap-4"
          >
            <v-btn
              color="primary"
              :disabled="form.processing"
              type="submit"
            >
              Resend Verification Email
            </v-btn>
            <v-spacer />
            <InertiaLink
              :href="route('profile.show')"
              class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Edit Profile
            </InertiaLink>

            <InertiaLink
              :href="route('logout')"
              method="post"
            >
              Log Out
            </InertiaLink>
          </div>
        </v-card-text>
      </v-form>
    </v-card>
  </AuthLayout>
</template>
